name: CI
on:
  push:
    tags:
      - v1
      - v1.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        id: var-name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Building and Deploying...
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: production
          deploy_branch: latest-release
          angular_dist_build_folder: dist/timerz
          base_href: /
